version: '3.8'
services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/node_modules
    restart: on-failure

  database:
    image: 'bitnami/postgresql:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: database
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
